language: java

dist: trusty

os:
  - linux

matrix:
  include:
    - jdk: openjdk8
      env: GRADLE_VERSION=4.10.3

install: true

before_script:
  - gradle wrapper --gradle-version=$GRADLE_VERSION
  
script:
  - ./gradlew clean build

sudo: true

cache:
  directories:
    - $HOME/.m2
