language: java

dist: trusty

os:
  - linux
  - osx
  - windows

jdk:
  - oraclejdk8

script:
  - gradle wrapper
  - ./gradlew wrapper --gradle-version 4.10

sudo: true

cache:
  directories:
    - $HOME/.m2
