language: java

dist: trusty

jdk:
  - oraclejdk8

before_install:
  - wget http://services.gradle.org/distributions/gradle-4.10.1-bin.zip
  - unzip -qq gradle-4.10.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-4.10.1
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v

script:
  - gradle check
  - gradle build

sudo: true

cache:
  directories:
    - $HOME/.m2
