language: java

dist: trusty

os:
  - linux
  - osx

jdk:
  - oraclejdk8

before_install:
  - sdk install gradle 4.10

script:
  - gradle check
  - gradle build

sudo: true

cache:
  directories:
    - $HOME/.m2
