Create table WPCs (
    valueStream VARCHAR(25),
    productionLine VARCHAR(50),
    productType VARCHAR(40),
    workPieceCarrierNumber int,
    PRIMARY KEY (valueStream , productionLine , productType, workPieceCarrierNumber)
);

Create table WPCCombos (
    valueStream VARCHAR(25),
    productionLine VARCHAR(50),
    productType VARCHAR(40),
    PRIMARY KEY (valueStream , productionLine , productType)
);

INSERT INTO WPCCombos (valueStream, productionLine, productType)
VALUES
    ('CRIN', 'Assembly Line 1', 'CRIN3'),
	('CRIN', 'Assembly Line 1', 'CRIN1'),
	('CRIN', 'Assembly Line 1', 'CAT'),
	('CRIN', 'Assembly Line 1', 'IVECO'),
	('CRIN', 'Assembly Line 1', 'DMAX'),
	('CRIN', 'Assembly Line 1', 'Tier3'),
	('CC', 'Assembly Line 1', 'CRIN3'),
	('CC', 'Assembly Line 1', 'CRIN1'),
	('CC', 'Assembly Line 1', 'CAT'),
	('CC', 'Assembly Line 1', 'IVECO'),
	('CC', 'Assembly Line 1', 'DMAX'),
	('CC', 'Assembly Line 1', 'Tier3'),
	('HDEV5', 'Assembly Line 1', 'CRIN3'),
	('HDEV5', 'Assembly Line 1', 'CRIN1'),
	('HDEV5', 'Assembly Line 1', 'CAT'),
	('HDEV5', 'Assembly Line 1', 'IVECO'),
	('HDEV5', 'Assembly Line 1', 'DMAX'),
	('HDEV5', 'Assembly Line 1', 'Tier3'),
	('HDEV6', 'Assembly Line 1', 'CRIN3'),
	('HDEV6', 'Assembly Line 1', 'CRIN1'),
	('HDEV6', 'Assembly Line 1', 'CAT'),
	('HDEV6', 'Assembly Line 1', 'IVECO'),
	('HDEV6', 'Assembly Line 1', 'DMAX'),
	('HDEV6', 'Assembly Line 1', 'Tier3'),
	('HPD5', 'Assembly Line 1', 'CRIN3'),
	('HPD5', 'Assembly Line 1', 'CRIN1'),
	('HPD5', 'Assembly Line 1', 'CAT'),
	('HPD5', 'Assembly Line 1', 'IVECO'),
	('HPD5', 'Assembly Line 1', 'DMAX'),
	('HPD5', 'Assembly Line 1', 'Tier3'),
	('CRIN', 'Final Assembly Line', 'CRIN3'),
	('CRIN', 'Final Assembly Line', 'CRIN1'),
	('CRIN', 'Final Assembly Line', 'CAT'),
	('CRIN', 'Final Assembly Line', 'IVECO'),
	('CRIN', 'Final Assembly Line', 'DMAX'),
	('CRIN', 'Final Assembly Line', 'Tier3'),
	('CC', 'Final Assembly Line', 'CRIN3'),
	('CC', 'Final Assembly Line', 'CRIN1'),
	('CC', 'Final Assembly Line', 'CAT'),
	('CC', 'Final Assembly Line', 'IVECO'),
	('CC', 'Final Assembly Line', 'DMAX'),
	('CC', 'Final Assembly Line', 'Tier3'),
	('HDEV5', 'Final Assembly Line', 'CRIN3'),
	('HDEV5', 'Final Assembly Line', 'CRIN1'),
	('HDEV5', 'Final Assembly Line', 'CAT'),
	('HDEV5', 'Final Assembly Line', 'IVECO'),
	('HDEV5', 'Final Assembly Line', 'DMAX'),
	('HDEV5', 'Final Assembly Line', 'Tier3'),
	('HDEV6', 'Final Assembly Line', 'CRIN3'),
	('HDEV6', 'Final Assembly Line', 'CRIN1'),
	('HDEV6', 'Final Assembly Line', 'CAT'),
	('HDEV6', 'Final Assembly Line', 'IVECO'),
	('HDEV6', 'Final Assembly Line', 'DMAX'),
	('HDEV6', 'Final Assembly Line', 'Tier3'),
	('HPD5', 'Final Assembly Line', 'CRIN3'),
	('HPD5', 'Final Assembly Line', 'CRIN1'),
	('HPD5', 'Final Assembly Line', 'CAT'),
	('HPD5', 'Final Assembly Line', 'IVECO'),
	('HPD5', 'Final Assembly Line', 'DMAX'),
	('HPD5', 'Final Assembly Line', 'Tier3'),
    ('CRIN', 'Magnet Line', 'CRIN3'),
	('CRIN', 'Magnet Line', 'CRIN1'),
	('CRIN', 'Magnet Line', 'CAT'),
	('CRIN', 'Magnet Line', 'IVECO'),
	('CRIN', 'Magnet Line', 'DMAX'),
	('CRIN', 'Magnet Line', 'Tier3'),
	('CC', 'Magnet Line', 'CRIN3'),
	('CC', 'Magnet Line', 'CRIN1'),
	('CC', 'Magnet Line', 'CAT'),
	('CC', 'Magnet Line', 'IVECO'),
	('CC', 'Magnet Line', 'DMAX'),
	('CC', 'Magnet Line', 'Tier3'),
	('HDEV5', 'Magnet Line', 'CRIN3'),
	('HDEV5', 'Magnet Line', 'CRIN1'),
	('HDEV5', 'Magnet Line', 'CAT'),
	('HDEV5', 'Magnet Line', 'IVECO'),
	('HDEV5', 'Magnet Line', 'DMAX'),
	('HDEV5', 'Magnet Line', 'Tier3'),
	('HDEV6', 'Magnet Line', 'CRIN3'),
	('HDEV6', 'Magnet Line', 'CRIN1'),
	('HDEV6', 'Magnet Line', 'CAT'),
	('HDEV6', 'Magnet Line', 'IVECO'),
	('HDEV6', 'Magnet Line', 'DMAX'),
	('HDEV6', 'Magnet Line', 'Tier3'),
	('HPD5', 'Magnet Line', 'CRIN3'),
	('HPD5', 'Magnet Line', 'CRIN1'),
	('HPD5', 'Magnet Line', 'CAT'),
	('HPD5', 'Magnet Line', 'IVECO'),
	('HPD5', 'Magnet Line', 'DMAX'),
	('HPD5', 'Magnet Line', 'Tier3'),
    ('CRIN', 'Test Line', 'CRIN3'),
	('CRIN', 'Test Line', 'CRIN1'),
	('CRIN', 'Test Line', 'CAT'),
	('CRIN', 'Test Line', 'IVECO'),
	('CRIN', 'Test Line', 'DMAX'),
	('CRIN', 'Test Line', 'Tier3'),
	('CC', 'Test Line', 'CRIN3'),
	('CC', 'Test Line', 'CRIN1'),
	('CC', 'Test Line', 'CAT'),
	('CC', 'Test Line', 'IVECO'),
	('CC', 'Test Line', 'DMAX'),
	('CC', 'Test Line', 'Tier3'),
	('HDEV5', 'Test Line', 'CRIN3'),
	('HDEV5', 'Test Line', 'CRIN1'),
	('HDEV5', 'Test Line', 'CAT'),
	('HDEV5', 'Test Line', 'IVECO'),
	('HDEV5', 'Test Line', 'DMAX'),
	('HDEV5', 'Test Line', 'Tier3'),
	('HDEV6', 'Test Line', 'CRIN3'),
	('HDEV6', 'Test Line', 'CRIN1'),
	('HDEV6', 'Test Line', 'CAT'),
	('HDEV6', 'Test Line', 'IVECO'),
	('HDEV6', 'Test Line', 'DMAX'),
	('HDEV6', 'Test Line', 'Tier3'),
	('HPD5', 'Test Line', 'CRIN3'),
	('HPD5', 'Test Line', 'CRIN1'),
	('HPD5', 'Test Line', 'CAT'),
	('HPD5', 'Test Line', 'IVECO'),
	('HPD5', 'Test Line', 'DMAX'),
	('HPD5', 'Test Line', 'Tier3'),